# Generated by Django 5.1.13 on 2025-10-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('pais', models.CharField(max_length=50)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('desarrolladora', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('industria', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('presupuesto_anual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Esports.equipo')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Esports.patrocinador')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='Gestor_Esports.equipo')),
                ('juegos', models.ManyToManyField(related_name='jugadores', to='Gestor_Esports.juego')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='Gestor_Esports.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidas_jugadas', models.IntegerField()),
                ('victorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('kda_promedio', models.FloatField()),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='Gestor_Esports.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_final', models.PositiveIntegerField()),
                ('puntos_obtenidos', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Esports.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='patrocinadores',
            field=models.ManyToManyField(related_name='equipos', through='Gestor_Esports.Contrato', to='Gestor_Esports.patrocinador'),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('premio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('equipos', models.ManyToManyField(related_name='torneos', through='Gestor_Esports.Participacion', to='Gestor_Esports.equipo')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='Gestor_Esports.juego')),
            ],
        ),
        migrations.AddField(
            model_name='participacion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestor_Esports.torneo'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True)),
                ('pais', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='Gestor_Esports.usuario')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('equipo', 'torneo')},
        ),
    ]
