# Generated by Django 5.1.13 on 2025-12-01 08:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('genero', models.CharField(max_length=80)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('fabricante', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('pais', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateField()),
                ('juegos', models.ManyToManyField(blank=True, related_name='equipos', to='Gestor_Esports.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, unique=True)),
                ('nombre_real', models.CharField(max_length=120)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(12)])),
                ('rol', models.CharField(choices=[('tank', 'Tanque'), ('dps', 'DPS'), ('support', 'Soporte'), ('igl', 'In-Game Leader')], max_length=60)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='Gestor_Esports.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('finalizado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='Gestor_Esports.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='Gestor_Esports.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('sensibilidad_raton', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('dpi', models.IntegerField(default=800)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='Gestor_Esports.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_local', models.IntegerField()),
                ('puntuacion_visitante', models.IntegerField()),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvps', to='Gestor_Esports.jugador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='Gestor_Esports.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('sector', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('equipos', models.ManyToManyField(blank=True, related_name='sponsors', to='Gestor_Esports.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('premio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='Gestor_Esports.juego')),
                ('plataformas', models.ManyToManyField(blank=True, related_name='torneos', to='Gestor_Esports.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='Gestor_Esports.torneo'),
        ),
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('cuota_pagada', models.BooleanField(default=False)),
                ('posicion_final', models.IntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Gestor_Esports.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Gestor_Esports.torneo')),
            ],
        ),
    ]
