# Generated by Django 5.1.13 on 2025-10-24 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Esports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
