# Generated by Django 5.1.13 on 2025-10-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Esports', '0003_alter_contrato_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
