# Generated by Django 5.1.13 on 2025-10-24 11:16

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Esports', '0004_alter_contrato_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='estadisticajugador',
            name='derrotas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajugador',
            name='kda_promedio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='estadisticajugador',
            name='partidas_jugadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticajugador',
            name='victorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='juego',
            name='desarrolladora',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='juego',
            name='fecha_lanzamiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='juego',
            name='genero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='rol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='posicion_final',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='puntos_obtenidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='industria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='presupuesto_anual',
            field=models.FloatField(default=100000.0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='premio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=8),
        ),
    ]
